steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-west1-docker.pkg.dev/microservices-course-444616/image-registry/orders-ms-prod -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DB_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-west1-docker.pkg.dev/microservices-course-444616/image-registry/orders-ms-prod',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/450974516733/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY